//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.SportScotland
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impact
    {
        public Impact()
        {
            this.ImpactRecords = new HashSet<ImpactRecord>();
        }
    
        public int ImpactId { get; set; }
        public string ImpactName { get; set; }
    
        public virtual ICollection<ImpactRecord> ImpactRecords { get; set; }
    }
}
