//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.SportScotland
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpactRecordBenificiary
    {
        public int ImpactRecordBenificiariesId { get; set; }
        public Nullable<int> ImpactRecordId { get; set; }
        public Nullable<int> BenificiaryId { get; set; }
    
        public virtual Benificiary Benificiary { get; set; }
        public virtual ImpactRecord ImpactRecord { get; set; }
    }
}
