//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.SportScotland
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpactRecord
    {
        public ImpactRecord()
        {
            this.ImpactRecordBenificiaries = new HashSet<ImpactRecordBenificiary>();
        }
    
        public int ImpactRecordId { get; set; }
        public Nullable<int> ImpactId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> StartDate { get; set; }
        public Nullable<int> EndDate { get; set; }
    
        public virtual Impact Impact { get; set; }
        public virtual ICollection<ImpactRecordBenificiary> ImpactRecordBenificiaries { get; set; }
    }
}
